sonar.projectKey=Marketplace_Marketplace_aa794b2a-16ef-417b-8fb7-5b5e4f1d9785
sonar.projectName=Marketplace
sonar.projectVersion=1.0
sonar.sources=.
sonar.language=js
sonar.host.url=http://staging.qservicesit.net:9000
sonar.login=sqa_0f902c5f18e0cd49eb43dc6c9f8c9318d7581d38
sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=**/*