export const commonIcons = {
  backButton: require('./backButton.png'),
  appLogo: require('./logo.png'),
  heart: require('./heart.png'),
  mic: require('./Audio.png'),
  cross: require('./cross-icon.png'),
  interest: require('./interest.png'),
  shopping: require('./Shopping.png'),
  filter: require('./filter.png'),
  camera: require('./camera.png'),
  location: require('./location.png'),
  business: require('./Business.png'),
  addToCart: require('./Add-to-Cart.png'),
  like: require('./like.png'),
  verify: require('./verify.png'),
  dislike: require('./dislike.png'),
  cross_black: require('./cross-icon-black.png'),
  logo:require('./zinabuLogo.png'),
  logoZinabu:require('./zinabuLogo1.png'),
  vectorHome:require('./Vector.png'),
  leftarrow:require('./left.png'),
  rightarrow:require('./right.png'),
  check:require('./check.png'),
  query:require('./query.png'),
  selectIcon:require('./selectIcon.png'),
  selectDown:require('./selectDown.png'),
  filterSet:require('./filterSet.png'),
  homeNew:require('./homenew.png'),
  editnew:require('./editNew.png'),
  frame:require('./frame.png')
  
};
